---
- hosts: 10.0.2.5
  gather_facts: yes
  remote_user: vagrant
  #sudo: yes
  become: true
  vars:
    target_user: vagrant
    RPath: "{{lookup('ansible_env','PATH')}}"
    RJavahome: "{{lookup('ansible_env','JAVA_HOME')}}"
    deb1: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main"
    path_url: http://ppa.launchpad.net/webupd8team/java/ubuntu
    jdk_dir: 8u131-b11
    jdk_archive: jdk-8u131-linux-x64.tar.gz
    jdk_local_dir: jdk1.8.0_131
    download_folder: /opt/oracle
    bin_dir: /usr/bin
    profile_path: /etc/profile.d
    java_name: "{{ download_folder }}/{{ jdk_local_dir }}"
    java_archive: "{{ download_folder }}/{{ jdk_archive }}"
    download_url: http://download.oracle.com/otn-pub/java/jdk/{{jdk_dir}}/{{jdk_archive}}
    java_version: 8
    java_subversion: 131
    java_build_custom: 11
    jdk_version_detail_custom: "{{ java_version }}u{{ java_subversion }}-b{{ java_build_custom }}"
    jdk_tarball_hash: d54c1d3a095b4ff2b6607d096fa80163
    jdk_tarball_url: "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail_custom }}/{{ jdk_tarball_hash }}/{{ jdk_archive }}"
    deb2: "deb-src {{path_url}} xenial main"
    es_java_install: false


  roles:
  - role: alokhom.j
    when: "ansible_os_family == 'Debian'"
    oracle_java_set_as_default: yes
